# MemeLord + Grafana Helm values
# Paigaldus: helm install memelord-arno . -n memelord-arno -f values-memelord-arno.yaml
# Teine instants: helm install memelord-arno2 . -n memelord-arno2 -f values-memelord-arno2.yaml

hostname: memelord-arno.ee-lte-1.codemowers.io
grafanaHostname: grafana-arno.ee-lte-1.codemowers.io
# Grafana OIDCClient nimi (secret: oidc-client-<grafanaOidcName>-owner-secrets). Tagasiühilduvuseks võib olla grafana-arno.
grafanaOidcName: grafana-arno

replicas: 1
